name: Issues Workflow
on:
    issues: 
        types: [opened]
jobs:
    process_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Respond to issue
              uses: actions/github-script@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                  const issueComment = `
                    Thank you for opening this issue. 
                    We will look into it soon.
                  `;
                  github.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: issueComment
                  });